export const sampleData = {
  samplestate: {
    rowCount: 254,
    colCount: 12,
    intColCount: 2,
    dataTypeCount: 5,
    quality: {
      valid: 2468,
      invalid: 58,
      missing: 14,
    },
    columnModel: [
      {
        displayName: "Item ID",
        name: "_c0",
        index: 2,
        dataType: {
          name: "string",
          baseType: "string",
          format: { disable: true, format: "(?s).*" },
          hasUnits: false,
          hasConstraints: false,
          isMandatory: false,
        },
        status: "RETAINED",
        columnType: "RAW",
        involved: false,
        widgets: {
          discrete: [
            { label: "b76f28aa151b41d6", count: 3 },
            { label: "38db3d961f884b7", count: 3 },
            { label: "230603da3105449", count: 3 },
          ],
          quality: [{ valid: 254, invalid: 0, missing: 0 }],
          aggregate: [{ min: "32", max: "32", avg: "32.0", mode: "b76f28aa151b41d6", categories: 244 }],
        },
        hidden: false,
        pii: false,
        personalData: { pii: false },
      },
      {
        displayName: "Name",
        name: "_c1",
        index: 3,
        dataType: {
          name: "string",
          baseType: "string",
          format: { disable: true, format: "(?s).*" },
          hasUnits: false,
          hasConstraints: false,
          isMandatory: false,
        },
        status: "RETAINED",
        columnType: "RAW",
        involved: false,
        widgets: {
          discrete: [
            { label: "VGA to HDMI Video adapter", count: 1 },
            { label: "CROSSFADE M-100 Over-the-Ear Headphones", count: 8 },
            { label: "725W 5.1-Ch. Network-Ready 4K", count: 14 },
          ],
          quality: [{ valid: 254, invalid: 0, missing: 0 }],
          aggregate: [{ min: "16", max: "91", avg: "50.098", mode: "VGA to HDMI Video adapter", categories: 49 }],
        },
        hidden: false,
        pii: false,
        personalData: { pii: false },
      },
      {
        displayName: "Brand",
        name: "_c2",
        index: 4,
        dataType: {
          name: "string",
          baseType: "string",
          format: { disable: true, format: "(?s).*" },
          hasUnits: false,
          hasConstraints: false,
          isMandatory: false,
        },
        status: "RETAINED",
        columnType: "RAW",
        involved: false,
        widgets: {
          discrete: [
            { label: "Samsung", count: 173 },
            { label: "Sony", count: 31 },
            { label: "Yamaha", count: 13 },
            { label: "Razer", count: 8 },
          ],
          quality: [{ valid: 254, invalid: 0, missing: 0 }],
          aggregate: [{ min: "4", max: "12", avg: "6.677", mode: "Samsung", categories: 12 }],
        },
        hidden: false,
        pii: false,
        personalData: { pii: false },
      },
      {
        displayName: "SKU_split_1",
        name: "_c11",
        index: 5,
        dataType: {
          name: "string",
          baseType: "string",
          format: { disable: true, format: "(?s).*" },
          hasUnits: false,
          hasConstraints: false,
          isMandatory: false,
        },
        status: "ADDED",
        columnType: "DERIVED",
        involved: false,
        widgets: {
          discrete: [{ label: "code", count: 254 }],
          quality: [{ valid: 254, invalid: 0, missing: 0 }],
          aggregate: [{ min: "4", max: "4", avg: "4.0", mode: "code", categories: 1 }],
        },
        hidden: false,
        pii: false,
        personalData: { pii: false },
      },
      {
        displayName: "SKU_split_2",
        name: "_c12",
        index: 6,
        dataType: {
          name: "number",
          baseType: "number",
          format: { disable: false, format: "##0" },
          hasUnits: false,
          hasConstraints: false,
          isMandatory: false,
        },
        status: "ADDED",
        columnType: "DERIVED",
        involved: false,
        widgets: {
          continuous: [
            { min: "13", max: "184", label: "13 - 184", count: 40 },
            { min: "184", max: "355", label: "184 - 355", count: 15 },
            { min: "355", max: "526", label: "355 - 526", count: 17 },
            { min: "526", max: "697", label: "526 - 697", count: 45 },
            { min: "697", max: "868", label: "697 - 868", count: 4 },
          ],
          quality: [{ valid: 254, invalid: 0, missing: 0 }],
          aggregate: [{ min: "13", max: "2569", avg: "1084" }],
        },
        hidden: false,
        pii: false,
        personalData: { pii: false },
      },
      {
        displayName: "Price",
        name: "_c4",
        index: 7,
        dataType: {
          name: "currency",
          baseType: "decimal",
          format: { disable: false, format: "##0.0##", ds: "." },
          unit: { disable: false, unit: "$", name: "Dollar", iCase: true, iSpace: true, isPrefix: true, isBase: false },
          hasUnits: false,
          hasConstraints: false,
          isMandatory: false,
        },
        status: "RETAINED",
        columnType: "RAW",
        involved: false,
        widgets: {
          continuous: [
            { min: "0.83", max: "33.0547", label: "$0.83 - $33.0547", count: 122 },
            { min: "33.0547", max: "65.2794", label: "$33.0547 - $65.2794", count: 17 },
            { min: "65.2794", max: "97.5041", label: "$65.2794 - $97.5041", count: 7 },
            { min: "97.5041", max: "129.7288", label: "$97.5041 - $129.7288", count: 4 },
            { min: "129.7288", max: "161.9535", label: "$129.7288 - $161.9535", count: 6 },
          ],
          quality: [{ valid: 196, invalid: 58, missing: 0 }],
          aggregate: [{ min: "$0.83", max: "$484.2", avg: "$86.658" }],
        },
        hidden: false,
        pii: false,
        personalData: { pii: false },
      },
      {
        displayName: "Country of Origin",
        name: "_c5",
        index: 8,
        dataType: {
          name: "string",
          baseType: "string",
          format: { disable: true, format: "(?s).*" },
          hasUnits: false,
          hasConstraints: false,
          isMandatory: false,
        },
        status: "RETAINED",
        columnType: "RAW",
        involved: false,
        widgets: {
          discrete: [
            { label: "South Korea", count: 183 },
            { label: "JAPAN", count: 49 },
            { label: "United States of America", count: 14 },
            { label: "ITALY", count: 8 },
          ],
          quality: [{ valid: 254, invalid: 0, missing: 0 }],
          aggregate: [{ min: "5", max: "24", avg: "10.37", mode: "South Korea", categories: 4 }],
        },
        hidden: false,
        pii: false,
        personalData: { pii: false },
      },
      {
        displayName: "Item Status",
        name: "_c6",
        index: 9,
        dataType: {
          name: "boolean",
          baseType: "string",
          format: { disable: false, format: "^(?i)(true|false|yes|no)$" },
          hasUnits: false,
          hasConstraints: false,
          isMandatory: false,
        },
        status: "RETAINED",
        columnType: "RAW",
        involved: false,
        widgets: {
          discrete: [
            { label: "Yes", count: 232 },
            { label: "No", count: 8 },
          ],
          quality: [{ valid: 240, invalid: 0, missing: 14 }],
          aggregate: [{ min: "2", max: "3", avg: "2.967", mode: "Yes", categories: 2 }],
        },
        hidden: false,
        pii: false,
        personalData: { pii: false },
      },
      {
        displayName: "Created At",
        name: "_c7",
        index: 10,
        dataType: {
          name: "datetime",
          baseType: "datetime",
          format: { disable: false, format: "dd-MM-yyyy HH:mm:ss" },
          hasUnits: false,
          hasConstraints: false,
          isMandatory: false,
        },
        status: "RETAINED",
        columnType: "RAW",
        involved: false,
        widgets: {
          continuous: [
            { min: "1605315600", max: "1605319200", label: "1 - 2", count: 44 },
            { min: "1605319200", max: "1605322800", label: "2 - 3", count: 87 },
            { min: "1605330000", max: "1605333600", label: "5 - 6", count: 123 },
          ],
          quality: [{ valid: 254, invalid: 0, missing: 0 }],
          aggregate: [{ min: "14-11-2020 01:47:46", max: "14-11-2020 05:38:03", avg: "14-11-2020 03:45:25" }],
        },
        hidden: false,
        pii: false,
        personalData: { pii: false },
      },
    ],
    data: [
      [
        "b76f28aa151b41d6",
        "VGA to HDMI Video adapter",
        "Sony",
        "code",
        1068,
        "$0.83",
        "JAPAN",
        "Yes",
        "14-11-2020 01:47:46",
      ],
      [
        "38db3d961f884b7",
        "CROSSFADE M-100 Over-the-Ear Headphones",
        "Startech.com",
        "code",
        1070,
        "$141.00",
        "United States of America",
        "",
        "14-11-2020 05:37:37",
      ],
      [
        "1279081212194ce8",
        "CROSSFADE M-100 Over-the-Ear Headphones",
        "Startech.com",
        "code",
        1071,
        "$126.69",
        "United States of America",
        "",
        "14-11-2020 05:37:38",
      ],
      [
        "e316b7b0b5994f13",
        "725W 5.1-Ch. Network-Ready 4K",
        "Yamaha",
        "code",
        1072,
        "$156.50",
        "JAPAN",
        "Yes",
        "14-11-2020 05:37:38",
      ],
      [
        "e316b7b0b5994f13",
        "725W 5.1-Ch. Network-Ready 4K",
        "Yamaha",
        "code",
        1072,
        "$156.50",
        "JAPAN",
        "Yes",
        "14-11-2020 05:37:38",
      ],
      [
        "2b871331b03f41ab",
        "CROSSFADE M-100 Over-the-Ear Headphones",
        "Sam Sung",
        "code",
        1073,
        "$387.55",
        "South Korea",
        "Yes",
        "14-11-2020 05:37:39",
      ],
      [
        "855cc83165144750",
        "CROSSFADE M-100 Over-the-Ear Headphones",
        "Startech",
        "code",
        1074,
        "$305.73",
        "United States of America",
        "",
        "14-11-2020 05:37:39",
      ],
      [
        "230603da3105449",
        "725W 5.1-Ch. Network-Ready 4K",
        "Razer",
        "code",
        1107,
        "$281.19",
        "ITALY",
        "No",
        "14-11-2020 05:38:00",
      ],
      [
        "5d5a3b530af5427",
        "725W 5.1-Ch. Network-Ready 4K",
        "Sony",
        "code",
        1108,
        "$57.07",
        "JAPAN",
        "Yes",
        "14-11-2020 05:38:01",
      ],
      [
        "b4c326d720e9428",
        "725W 5.1-Ch. Network-Ready 4K",
        "Yamaha",
        "code",
        1109,
        "$152.93",
        "JAPAN",
        "Yes",
        "14-11-2020 05:38:01",
      ],
      [
        "2b871331b03f41ab",
        "CROSSFADE M-100 Over-the-Ear Headphones",
        "Sam Sung",
        "code",
        1073,
        "$387.55",
        "South Korea",
        "Yes",
        "14-11-2020 05:37:39",
      ],
      [
        "855cc83165144750",
        "CROSSFADE M-100 Over-the-Ear Headphones",
        "Startech",
        "code",
        1074,
        "$305.73",
        "United States of America",
        "",
        "14-11-2020 05:37:39",
      ],
      [
        "230603da3105449",
        "725W 5.1-Ch. Network-Ready 4K",
        "Razer",
        "code",
        1107,
        "$281.19",
        "ITALY",
        "No",
        "14-11-2020 05:38:00",
      ],
      [
        "5d5a3b530af5427",
        "725W 5.1-Ch. Network-Ready 4K",
        "Sony",
        "code",
        1108,
        "$57.07",
        "JAPAN",
        "Yes",
        "14-11-2020 05:38:01",
      ],
      [
        "b4c326d720e9428",
        "725W 5.1-Ch. Network-Ready 4K",
        "Yamaha",
        "code",
        1109,
        "$152.93",
        "JAPAN",
        "Yes",
        "14-11-2020 05:38:01",
      ],
      [
        "230603da3105449",
        "725W 5.1-Ch. Network-Ready 4K",
        "Razer",
        "code",
        1107,
        "$281.19",
        "ITALY",
        "No",
        "14-11-2020 05:38:00",
      ],
      [
        "5d5a3b530af5427",
        "725W 5.1-Ch. Network-Ready 4K",
        "Sony",
        "code",
        1108,
        "$57.07",
        "JAPAN",
        "Yes",
        "14-11-2020 05:38:01",
      ],
      [
        "b4c326d720e9428",
        "725W 5.1-Ch. Network-Ready 4K",
        "Yamaha",
        "code",
        1109,
        "$152.93",
        "JAPAN",
        "Yes",
        "14-11-2020 05:38:01",
      ],
    ],
  },
  response_status: {
    status: "success",
    status_code: 2000,
  },
}
